begin
	EXECUTE IMMEDIATE 'DROP TABLE   CLIENTE CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/
begin
	EXECUTE IMMEDIATE 'DROP TABLE   PRODUCTO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/
begin
	EXECUTE IMMEDIATE 'DROP TABLE   SERVICIO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/
begin
	EXECUTE IMMEDIATE 'DROP TABLE   COMPRA CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/
begin
	EXECUTE IMMEDIATE 'DROP TABLE   COMPRAPRODUCTO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/
begin
	EXECUTE IMMEDIATE 'DROP TABLE   COMPRASERVICIO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;
/



create table PRODUCTO(
	K_ID NUMBER(10) NOT NULL,
	N_NOMBRE VARCHAR(20) NOT NULL,
	Q_PRECIO NUMBER(11,2) NOT NULL,
	N_DESCRIPCION VARCHAR(300) NOT NULL, 
	N_CATEGORIA NUMBER(10) NOT NULL
);

ALTER TABLE  PRODUCTO 
 ADD CONSTRAINT PK_PRODUCTO
	PRIMARY KEY (K_ID) 
 USING INDEX
;


create table CLIENTE(
	K_ID NUMBER(10) NOT NULL,
	N_NOMBRE VARCHAR(20) NOT NULL,
	Q_CEDULA NUMBER(10) NOT NULL,
	N_CATEGORIA VARCHAR(20) NOT NULL
);


ALTER TABLE  CLIENTE 
 ADD CONSTRAINT PK_CLIENTE
	PRIMARY KEY (K_ID) 
 USING INDEX
;

create table COMPRA(
	K_ID_COM  NUMBER(10) NOT NULL,
	K_ID_CLIENTE_COM NUMBER(10) NOT NULL,
	N_FECHA_COM DATE NOT NULL,
	Q_TOTAL_COM NUMBER(10) NOT NULL,
	N_CATEGORIA_COM VARCHAR(20) NOT NULL
);

ALTER TABLE  COMPRA 
 ADD CONSTRAINT PK_COMPRA
	PRIMARY KEY (K_ID_COM) 
 USING INDEX
;


create table COMPRAPRODUCTO(
	K_ID_PRODUCTO_CP NUMBER(10) NOT NULL,
	K_ID_COMPRA_CP NUMBER(10) NOT NULL,
	Q_TOTAL_CP NUMBER(10) NOT NULL
);




alter table COMPRAPRODUCTO add foreign key (K_ID_PRODUCTO_CP) references PRODUCTO(K_ID);
alter table COMPRAPRODUCTO add foreign key (K_ID_COMPRA_CP) references COMPRA(K_ID_COM);

alter table COMPRA add foreign key (K_ID_CLIENTE_COM) references CLIENTE(K_ID);

